lightsail_instance_name     = "fishbits_wordpress"
lightsail_availability_zone = "us-west-2b"
lightsail_blueprint         = "wordpress"
lightsail_ip_address_type   = "ipv4"
lightsail_bundle_id         = "micro_2_0"
lightsail_static_ip_name    = "fishbits_static_ip"